name: CiPipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15
      
      - name: Install dependencies
        run: npm install
        working-directory: codebase/rdicidr-0.1.0

      - name: Run Linter
        run: npm run lint
        working-directory: codebase/rdicidr-0.1.0

      - name: Run Prettier
        run: npm run prettier -- --write
        working-directory: codebase/rdicidr-0.1.0

      - name: Run Tests
        run: CI=true npm run test
        working-directory: codebase/rdicidr-0.1.0

      - name: Project build
        run: npm run build
        working-directory: codebase/rdicidr-0.1.0